version: "3.9"
services:

#  node:
#    container_name: node
#    image: node:lts
#    working_dir: /home/node
#    volumes:
#      - ./node/nanoid:/home/node
#    command: bash -c "npm install && node index"
#    tty: true
#    restart: unless-stopped
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www
      - ./acme:/var/acme
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"